### ISSUE TITLE
How to call nordlicht's output?

### ISSUE THREAD

**Issue by blinry** [nordlicht/nordlicht#28]
In the documentation, I use the term "barcode" to describe the things generated by nordlicht. Some people argued that this term seems to imply some form of digital scanning; some asked whether they could "scan" these barcodes with their phones. And it's true: It's not a code at all.

I adopted the term from the moviebarcode Tumblr without thinking much about it. To avoid confusion, we could migrate to another term, and I'd like to brainstorm ideas here.

There are [Moodbars](https://en.wikipedia.org/wiki/Moodbar). The postfix "bar" sounds okay, but I guess we could also use "strip"? [Theodore Gray](http://blog.wolfram.com/2013/08/13/a-visit-to-disneys-magic-kingdom/) calls similar things "color map", using a postfix which I also like as "map" highlights the navigational properties of the image. I'd like to avoid "movie" or "video", as the library could be extended to handle audio files in the future.

"navigation bar"? "media map"? "multimedia strip"? I'd love to hear your suggestions.

**Comment by blinry** [comment]
In a way, these images serve a similar purpose as thumbnails, and could be used as such.

*thumbbar*? As you can use it to "thumb through" a multimedia file? ;-)

**Comment by blinry** [comment]
Offtopic: Anyone using GNOME's Nautilus? Turns out there's a really easy way to enable nordlicht thumbnails: 2fd3b28

**Comment by Kasalehlia** [comment]
I think the word "slice" fits as part of the final name. It describes the slices of the movie that are used as well as each frame being placed next to each other like slices of bread to form a loaf. So I suggest something like slicebar or slicestrip. Not nice to pronounce but I think it fits.

**Comment by rohieb** [comment]
On 02.02.2016 00:25, Kasalehlia wrote:
> I think the word "slice" fits as part of the final name. It describes the slices
> of the movie that are used as well as each frame being placed next to each other
> like slices of bread to form a loaf.

Okay, so with this metaphor, the picture as a whole would be the loaf, and we
are looking for a word that describes the picture as a whole. So why not call it
"nordloaf", "thumbloaf", or "loafnail"?

**Comment by blinry** [comment]
I'm not really fond of those bread analogies :> IMHO, the term should be mostly self-explanatory, and while "slice" or "loaf" is clever and fitting, I'm afraid it's not obvious what they refer to here.

How do you like "timebar"? What's definitely always there is the linear mapping of time to the x-direction of the image.

**Comment by rohieb** [comment]
To be honest, nordlicht has been around for so long now, I call the output in my head like this all the time ^^

**Comment by blinry** [comment]
I do, as well! :-) This term is just for the one introduction sentence describing the concept to new people, like on the homepage, in software package descriptions. I think I like **"timebar"**. It's rather intuitive and has two easy syllables, like "thumbnail". Let's go with it until we come up with something better! :)

**Comment by a-tze** [comment]
thumbline ;)
