### ISSUE TITLE
Iterative nordlicht creation

### ISSUE THREAD

**Issue by cinemast** [nordlicht/nordlicht#41]
Hi!

It would be great to have a function that creates the nordlicht iteratively instead of blocking until the whole image is prepared. 

Something like 

```
//returns 1 on finish, 0 if it needs processing, -1 on error.
int nordlicht_process(nordlicht* n);
```

**Comment by blinry** [comment]
In the past, I tried two approaches similar to this:

- a [`nordlicht_step`](https://github.com/nordlicht/nordlicht/blob/bc5ad1b478c811cfca982b51d53f29e2ae7630ef/src/nordlicht.h#L24) function which would generate a small portion of the nordlicht and then return a float between 0 and 1 depending on how much was already generated. This behaved closely to what you suggest.
- before that, [`nordlicht_input`](https://github.com/nordlicht/nordlicht/blob/2600110b0b1ae1f412fe7652f57a249391968ad8/src/nordlicht.h#L32) would start generation in an internal thread as soon as the input file was set. Progress could be read via `nordlicht_progress`, like currently.

In the end, I decided this was all adding unnecessary complexity. If the user wants non-blocking generation, they could start their own thread (like [the tool currently does](https://github.com/nordlicht/nordlicht/blob/af2ff66fd4c8486977d578c1017a719de7b01f20/main.c#L231)). I'm quite happy with this, as it's the simplest possible solution. Do you think it's very inconvenient?

**Comment by cinemast** [comment]
The `nordlicht_step` is exactly what I was looking for. It just gives the user of the API more flexibility and also prevents synchronisation efforts. I think that both methods can be provided without much effort, which gives the user of the API full flexibility.

**Comment by blinry** [comment]
I'd like to understand what you would use this for. I'd argue it's always a bad idea to do this in a blocking manner in video players. Can you explain your use case?

**Comment by cinemast** [comment]
This could avoid useless additional threads, to allow the application working and doing additional stuff without having to thread just for this one blocking call. Most video processing APIs work that way. For example you would also not want ffmpeg or OpenCV to do the encoding just in one call. Most of Video APIs work on a per frame basis to give the user more flexibility. 

I am not saying it can't be done using the current API its just that now, most of the time you have threads and synchronisation issues for no additional benefit.

**Comment by cinemast** [comment]
Additionally I can provide you with a snipped from the project where this is a problem for me:

With an incremental step function, I wouldn't have to spawn another thread. Also your main function of nordlicht could work without any threads. I think this is a benefit.

```
#include "Moodbar.h"
#include <iostream>

using namespace fivr;
using namespace std;

Moodbar::Moodbar(const char* workingDirectory) : FivrNativePlugin(workingDirectory)
{
    this->AddConfigKey("input", "", TYPE_FILE);
    this->AddConfigKey("width", "1000", TYPE_INT);
    this->AddConfigKey("height", "300", TYPE_INT);
    this->AddConfigKey("style", "horizontal,vertical,spectrogram,middlecolumn", TYPE_ENUM);
    this->AddConfigKey("thumbnails", "0", TYPE_BOOL);
    m_styles = NULL;
    m_nordthread = NULL;
}

Moodbar::~Moodbar()
{
    if (m_styles != NULL)
        delete m_styles;

    if (m_nordlicht != NULL)
        nordlicht_free(m_nordlicht);
    this->Stop();
}

bool Moodbar::UpdateConfigKey(const string &key, const string &value)
{
    if (key == "input")
        m_input = value;
    else if(key == "width")
        m_width = ConvertString<int>(value);
    else if (key == "height")
        m_height = ConvertString<int>(value);
    else if(key == "style")
        m_style = value;
    else if(key == "thumbnails")
        m_thumbnails = ConvertString<bool>(value);
    else
        return false;

    return true;
}

bool Moodbar::Init()
{
    m_nordlicht = nordlicht_init(m_input.c_str(), m_width, m_height);

    if (m_nordlicht == NULL)
    {
        this->SetInfo("Error opening file for nordlicht");
        return false;
    }

    int styles = 1;
    if(m_thumbnails)
    {
        styles = 2;
        m_styles = new nordlicht_style[2];
        m_styles[1] = NORDLICHT_STYLE_THUMBNAILS;
    }
    else
        m_styles = new nordlicht_style[1];

    if (m_style == "vertical")
        m_styles[0] = NORDLICHT_STYLE_VERTICAL;
    else if (m_style == "spectrogram")
        m_styles[0] = NORDLICHT_STYLE_SPECTROGRAM;
    else if (m_style == "middlecolumn")
        m_styles[0] = NORDLICHT_STYLE_MIDDLECOLUMN;
    else
        m_styles[0] = NORDLICHT_STYLE_HORIZONTAL;

    if (nordlicht_set_style(m_nordlicht, m_styles, styles) != 0)
    {
        this->SetInfo("Error setting styles");
        return false;
    }
    return true;
}

bool Moodbar::Process()
{
    if (m_nordthread == NULL)
    {
        m_result = 1;
        m_nordthread = new std::thread(&Moodbar::ProcessThread, this);
        return true;
    }
    else
    {
        if (m_result == 1)
        {
            this->UpdateProgress(nordlicht_progress(m_nordlicht));
            return true;
        }
        else if (m_result == 0)
        {
            string filename = "nordlicht_"+m_style+".png";
            nordlicht_write(m_nordlicht, this->GetAbsoluteFilePath(filename).c_str());
            this->AddOutputFile(filename);
        }
        else if (m_result != 0)
            this->SetInfo(nordlicht_error());
        return false;
    }
}

void Moodbar::ProcessThread()
{
    m_result = nordlicht_generate(m_nordlicht);
}

const char* Moodbar::GetVersion()
{
    return "1.0.0";
}
```

**Comment by blinry** [comment]
Thanks for providing this example, it's very helpful to see this in context. If I understand correctly, you'd then like the `nordlicht_step` function to do "as little work as possible"? That is, generate one additional pixel column of the nordlicht, or build one entry of the keyframe index, if we need to build it. So that your `Process()` blocks as short as possible.

I also agree that it would be nice to have this in the nordlicht tool, so we don't have to use any threads!

I'm glad that the rest of the current API looks usable! :-) I considered letting the user supply the style specification directly as a string (like in the command line tool, for example "horizontal+thumbnails"), which would save you a lot of code. But while this would be more comfortable, this would have the disadvantage that the "correctness" of the style cannot be checked at compile time at all, which is why I think this is a bad idea. What do you think?

**Comment by cinemast** [comment]
Thank you very much! This was exactly what I was talking about. It is also great that you kept the original function alive for convenience.
