### ISSUE TITLE
Cannot open files with a colon ":" in names because of FFmpeg's protocol syntax.

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#55]
Prepending “file:” to the name helps.

**Comment by blinry** [comment]
Thanks for reporting! I see how this could be a problem. Prepending `./` also helps. Huh, I wonder whether there is some standard way to handle this issue in tools based on FFmpeg. We could manually check whether the filename contains "://" and internally prepend "file:" in all other cases?

Whoa, I didn't realize one could do something like

    nordlicht -w 100 http://video.webmfiles.org/big-buck-bunny_trailer.webm -o bbb.png

It's obviously quite slow (maybe non-ideal seeking for streamed sources?), but it does work!
