### ISSUE TITLE
mpv-nordlicht.lua: clicking works anywhere on the video image, not just in the barcode.

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#56]
Instead of pausing the video, clicking it seeks in the barcode.

**Comment by rohieb** [comment]
Right, the "seek" functionality currently only looks at the x value of the mouse pointer… But iirc, right-clicking should still pause the video?

**Comment by aleksejrs** [comment]
> But iirc, right-clicking should still pause the video?

It does, thanks (and left-clicking does not work in MPlayer2).

**Comment by blinry** [comment]
But I agree that this behaviour was confusing. Thanks for reporting this! Fixed in 8662712.
