### ISSUE TITLE
FFMPEG 3.0 support

### ISSUE THREAD

**Issue by cinemast** [nordlicht/nordlicht#60]
Hi!

At Debian we currently migrate towards ffmpeg 3.0. I prepared a patch which fixes errors and some warnings (although not all of them).

Maybe you might apply it for the next upstream release.

http://anonscm.debian.org/cgit/pkg-multimedia/nordlicht.git/tree/debian/patches/0003-ffmpeg3.patch

**Comment by cinemast** [comment]
Hold on, the path might still require some work. Currently with the patch applied, the program is segfaulting.

**Comment by blinry** [comment]
Thanks for your work on this! I'll wait until you give your okay. Or, if you can't find the problem easily, I can also help with debugging.

**Comment by cinemast** [comment]
I will follow a pull-request with the changes, if thats ok for you.

**Comment by cinemast** [comment]
Nevermind, I saw too late there is already a patch available on master:

https://github.com/nordlicht/nordlicht/commit/6e534a0c273756b88eecea7f510b6aa8a62dd789

I will keep the current Debian patch and remove it after the next release.
