### ISSUE TITLE
nordlich: Cloud not open output codec. 

### ISSUE THREAD

**Issue by xkpd3** [nordlicht/nordlicht#62]
Hello,

I have installed nordling on debian (1:0.4.4-dmo3) via package and I also compiled it myself. Both results in the error message:

```
nordlicht: Cloud not open output codec.
```

I found this error here in [image.c#L269](https://github.com/nordlicht/nordlicht/blob/cad4130b1626c1f8eb921da9375036e30fd50475/src/image.c#L269). Which leads to the assumption that I have a wrong version of libavcodec installed.

```
$ dpkg-query -f '${binary:Package} (${Version})\n' -W | grep '^libav'
libav-tools (7:3.1.3-1)
libavc1394-0:amd64 (0.5.4-4)
libavcodec-dev:amd64 (10:3.1.3-dmo3)
libavcodec-extra-56:amd64 (6:11.7-1~deb8u1)
libavcodec56:amd64 (10:2.6.9-dmo1)
libavcodec57:amd64 (10:3.1.3-dmo3)
libavdevice57:amd64 (10:3.1.3-dmo3)
libavfilter5:amd64 (10:2.6.9-dmo1)
libavfilter6:amd64 (10:3.1.3-dmo3)
libavformat-dev:amd64 (10:3.1.3-dmo3)
libavformat56:amd64 (10:2.6.9-dmo1)
libavformat57:amd64 (10:3.1.3-dmo3)
libavresample2:amd64 (10:2.6.9-dmo1)
libavresample3:amd64 (10:3.1.3-dmo3)
libavutil-dev:amd64 (10:3.1.3-dmo3)
libavutil54:amd64 (10:2.6.9-dmo1)
libavutil55:amd64 (10:3.1.3-dmo3)
```

What am I missing?

Best Regards,
Stefan

**Comment by rohieb** [comment]
Hmm, is there a reason why you were using deb-multimedia.org builds instead of the official Debian builds? I'm not sure, but I think dmo packages libav instead of ffmpeg in the "ffmpeg" packages.

**Comment by rohieb** [comment]
Wait no, I can reproduce it on my Debian with the official ffmpeg builds.

@blinry: avcodec_open2 returns 1 for me, any clue what is going on here?

**Comment by rohieb** [comment]
Huh. #63 works for me.

**Comment by xkpd3** [comment]
@rohieb, I can confirm. #63 works here too. Thank you!
