### ISSUE TITLE
mpv-nordlicht.lua: Make sure the file name won't be too long before generating the file

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#65]
".nordlicht.png" adds length to the file name, which can make it impossible to put the file near the video, but the programs crash only after generating the image.

**Comment by rohieb** [comment]
Hmm yes… thinking of #43, we could move to a hash-based filename instead to work around this. @blinry, thoughts?

**Comment by blinry** [comment]
@aleksejrs, in which context would the length of the filename be a problem? On file systems with length restrictions? I think this problem then also applies to the command line tool, which also uses `$video.nordlicht.png` as a default output name.

**Comment by aleksejrs** [comment]
> to a hash-based filename

Only if shortest possible end of the name is replaced with a hash.

**Comment by aleksejrs** [comment]
> @aleksejrs, in which context would the length of the filename be a problem? On file systems with length restrictions?

There is a 255 byte limit on Linux, apparently only on a single segment, not on the whole path?

`touch 123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMN` works in any directory,
`touch 123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNO` says:
`touch: cannot touch '123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNOPQRST123456789ABCDEFGHIJKLMNO': File name too long`

**Comment by aleksejrs** [comment]
> I think this problem then also applies to the command line tool, which also uses $video.nordlicht.png as a default output name.

The script uses a temporary file, I don't know about the tool itself.

**Comment by blinry** [comment]
"Can't touch this"! ;-) Thanks for reporting, I'll look into this!

**Comment by rohieb** [comment]
On 08.01.2017 13:50, aleksejrs wrote:
> There is a 255 byte limit on Linux, apparently only on a single segment,
> not on the whole path?

Yes, I'm having strange issues like this all the time on my old
ecryptfs, its limit seems to be at 160 chars. And don't forget FAT16 ;-) :P

**Comment by aleksejrs** [comment]
IIRC, ecryptfs stores the encrypted file name in the file name. Encfs does not have that problem, but it's slow.

**Comment by blinry** [comment]
338f713d07f011912bff90af3d439588cfd17987 fixes this problem in the mpv-nordlicht integration. If you feel the default behaviour of the tool to put the PNG at `videofilename.nordlicht.png` is problematic, please reopen this issue.

**Comment by aleksejrs** [comment]
> 338f713 fixes this problem in the mpv-nordlicht integration.

I don't like that change:

1. Because of the md5, renaming a video will cause re-generation. Slitscan mode, for example, is very slow.
2. Because of the cache directory, moving the video to a different user will cause re-generation.
3. It doesn't use the existing .nordlicht.png files generated by the previous version.
4. Having the nordlicht near the video makes it easy to copy or send them both.
5. I sometimes use nordlichts to compare similar videos (when editing, or when downloading several versions encoded differently).

**Comment by aleksejrs** [comment]
> 338f713 fixes this problem in the mpv-nordlicht integration.

I don't like that change, see https://github.com/nordlicht/nordlicht/issues/43#issuecomment-275076961
