### ISSUE TITLE
Aspect ratio for thumbnails is sometimes not calculated correctly

### ISSUE THREAD

**Issue by blinry** [nordlicht/nordlicht#66]
Example [here](https://twitter.com/nordlichtbot/status/818067987416616960), the thumbnails' aspect ratio is clearly too high. I'm not sure about the reason yet.

I noticed that `youtube-dl` says "fixing aspect ratio" when downloading some of these, so maybe there's some codec magic going on. The resulting file plays correctly in mpv.

**Comment by rohieb** [comment]
That link says `--style=slitscan+middlecolumn+spectrogram`, so no thumbnailing is involved here…?

**Comment by blinry** [comment]
Ah, I didn't explain this: The thumbnail aspect ratio is also used for the movement speed of the slitscan line, so they conceptually have a very similar structure.

**Comment by blinry** [comment]
Turns out this bug doesn't actually exist. The video in the example above is actually in portrait mode, and the thumbnail aspect ratio is correct. Well, this was easy! :D
