### ISSUE TITLE
Option to rotate the picture?

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#71]
“Vertical” and “verticalthird” styles “`compress frames to horizontal lines and rotate them counterclockwise by 90 degrees`”.

That's useful for narrow output (including player seekbars), but https://twitter.com/nordlichtbot generates almost square pictures sometimes, and I think in that case it would make much more sense to keep the horizontal lines horizontal if that's the only style used (recall the explanation of how the emoticon `:-)` works, which includes turning your head instead of imagining the emoticon itself rotated).

On the other hand, I use nordlicht only for seekbars, so I don't see enough value in the “moodbar” use, where comparison may require consistent rotation (I got this idea when trying to guess what the videos were about).

What do you think?

(Edited a day later because I confused the horizontal and vertical styles)

**Comment by blinry** [comment]
In this case, I'd rather have the user do a quick `mogrify -transpose output.png`, or using an image editor to do this :-) "One tool for one job", isn't that what they say? I would like to try to keep nordlicht's feature set as small and concise as possible, which will make maintenance easier and offer less living space for 
nasty bugs! :-P Please feel free to re-open this issue if you disagree!
But I agree that a top-down running vertical-style nordlicht looks cool and requires less thought! :-)
