### ISSUE TITLE
Clarify the vertical style example

### ISSUE THREAD

**Issue by aleksejrs** [nordlicht/nordlicht#72]
Both --help and man have an example about the "vertical" style.  I suggest that it remind the reader *how* the frames are compressed into columns, even if it's written about in the previous paragraph, because the style name names the direction of the compression "force", but the output of the vertical style is columns because of rotation
```
Styles:
  horizontal     compress frames to vertical lines and append them
  vertical       compress frames to horizontal lines and rotate them counterclockwise by 90 degrees
```

```
nordlicht video.mp4 -s vertical                       compress individual frames to columns
```

**Comment by blinry** [comment]
Thanks for this input. I went in a different direction to avoid confusion: In the example, I point the user to the styles section "above".

I have never been really happy with the names "horizontal" and "vertical" (in the beginning I constantly confused them myself ;-), and I welcome any better ideas! "left" and "down"?

**Comment by aleksejrs** [comment]
"Left" and "down" would be confusing because of "middlecolumn".
